# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('visible', models.SmallIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countrytable',
            fields=[
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('countrycode', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'countrytable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenguinnessPhotos',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('credit', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'penguinness_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deptha', models.CharField(blank=True, max_length=60, null=True)),
                ('sd_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sample_size_depth', models.IntegerField(blank=True, null=True)),
                ('depthsample', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('durationa', models.CharField(blank=True, max_length=200, null=True)),
                ('sd_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sample_size_duration', models.IntegerField(blank=True, null=True)),
                ('durationsample', models.CharField(blank=True, max_length=200, null=True)),
                ('methods', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=60, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sitetable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=60)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'sitetable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speciestable',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('latin', models.CharField(blank=True, max_length=60, null=True)),
                ('species', models.CharField(blank=True, max_length=60, null=True)),
                ('mass', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('visible', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('oisooupas', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speciestable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('position', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.SmallIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('position', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subgroup',
                'managed': False,
            },
        ),
    ]
